## Ejercicio 1
Calcula la proporción de visitantes los dominogos del siguiente dataset.
Pasos recomendados:
- Entender el tipo de los datos
- Transformar el tipo de las fechas de los datos
- Crear una columna nueva llamada weekday

In [281]:
import pandas as pd

import numpy as np


# Run this cell to create the dataset
from datetime import datetime

dates = [f"2026-01-{day:02d}" for day in range(1, 32)] # day 2 digitos
visitors = [270, 470, 300, 420, 390, 360, 330, 300, 420, 490, 480, 410, 460, 480, 220, 450, 390, 430, 400, 350, 380, 290, 330, 490, 420, 470, 340, 500, 260, 420, 400]

df_visitations = pd.DataFrame({'date': dates, 'visitors': visitors})
df_visitations.head()

         date  visitors
0  2026-01-01       270
1  2026-01-02       470
2  2026-01-03       300
3  2026-01-04       420
4  2026-01-05       390

In [282]:
df_visitations['date'] = pd.to_datetime(df_visitations['date'])

In [283]:
df_visitations['weekday'] = df_visitations['date'].dt.day
df_visitations['weekday_name'] = df_visitations['date'].dt.day_name()

In [284]:
df_visitations

         date  visitors  weekday weekday_name
0  2026-01-01       270        1     Thursday
1  2026-01-02       470        2       Friday
2  2026-01-03       300        3     Saturday
3  2026-01-04       420        4       Sunday
4  2026-01-05       390        5       Monday
5  2026-01-06       360        6      Tuesday
6  2026-01-07       330        7    Wednesday
7  2026-01-08       300        8     Thursday
8  2026-01-09       420        9       Friday
9  2026-01-10       490       10     Saturday
10 2026-01-11       480       11       Sunday
11 2026-01-12       410       12       Monday
12 2026-01-13       460       13      Tuesday
13 2026-01-14       480       14    Wednesday
14 2026-01-15       220       15     Thursday
15 2026-01-16       450       16       Friday
16 2026-01-17       390       17     Saturday
17 2026-01-18       430       18       Sunday
18 2026-01-19       400       19       Monday
19 2026-01-20       350       20      Tuesday
20 2026-01-21       380       21    Wednesday
21 2026-01-22       290       22     Thursday
22 2026-01-23       330       23       Friday
23 2026-01-24       490       24     Saturday
24 2026-01-25       420       25       Sunday
25 2026-01-26       470       26       Monday
26 2026-01-27       340       27      Tuesday
27 2026-01-28       500       28    Wednesday
28 2026-01-29       260       29     Thursday
29 2026-01-30       420       30       Friday
30 2026-01-31       400       31     Saturday

In [285]:
df_visitations['date'].dt.strftime("%A") # Dia de la semana

0      Thursday
1        Friday
2      Saturday
3        Sunday
4        Monday
5       Tuesday
6     Wednesday
7      Thursday
8        Friday
9      Saturday
10       Sunday
11       Monday
12      Tuesday
13    Wednesday
14     Thursday
15       Friday
16     Saturday
17       Sunday
18       Monday
19      Tuesday
20    Wednesday
21     Thursday
22       Friday
23     Saturday
24       Sunday
25       Monday
26      Tuesday
27    Wednesday
28     Thursday
29       Friday
30     Saturday
Name: date, dtype: str

In [286]:
df_visitations['date'].dt.strftime("The date is %a, %d, %m, the year is %y")

0     The date is Thu, 01, 01, the year is 26
1     The date is Fri, 02, 01, the year is 26
2     The date is Sat, 03, 01, the year is 26
3     The date is Sun, 04, 01, the year is 26
4     The date is Mon, 05, 01, the year is 26
5     The date is Tue, 06, 01, the year is 26
6     The date is Wed, 07, 01, the year is 26
7     The date is Thu, 08, 01, the year is 26
8     The date is Fri, 09, 01, the year is 26
9     The date is Sat, 10, 01, the year is 26
10    The date is Sun, 11, 01, the year is 26
11    The date is Mon, 12, 01, the year is 26
12    The date is Tue, 13, 01, the year is 26
13    The date is Wed, 14, 01, the year is 26
14    The date is Thu, 15, 01, the year is 26
15    The date is Fri, 16, 01, the year is 26
16    The date is Sat, 17, 01, the year is 26
17    The date is Sun, 18, 01, the year is 26
18    The date is Mon, 19, 01, the year is 26
19    The date is Tue, 20, 01, the year is 26
20    The date is Wed, 21, 01, the year is 26
21    The date is Thu, 22, 01, the year is 26
22    The date is Fri, 23, 01, the year is 26
23    The date is Sat, 24, 01, the year is 26
24    The date is Sun, 25, 01, the year is 26
25    The date is Mon, 26, 01, the year is 26
26    The date is Tue, 27, 01, the year is 26
27    The date is Wed, 28, 01, the year is 26
28    The date is Thu, 29, 01, the year is 26
29    The date is Fri, 30, 01, the year is 26
30    The date is Sat, 31, 01, the year is 26
Name: date, dtype: str

## Ejercicio 2
Para entender el rendimiento de cada tienda, calcula las ganancias por venta medias de los datos del ejercicio.

In [287]:
#run this cell to create the dataset
df_exp = pd.DataFrame({
    'Shop Name': ['Madrid', 'Barcelona', 'Sevilla'],
    'Monday': ["100€", "200€", "150€"],
    'Tuesday': ["90€", "80€", "70€"],
    'Wednesday': ["120€", "150€", "110€"],
    'Thursday': ["100€", "90€", "120€"],
    'Friday': ["70€", "110€", "130€"]
})

df_exp

   Shop Name Monday Tuesday Wednesday Thursday Friday
0     Madrid   100€     90€      120€     100€    70€
1  Barcelona   200€     80€      150€      90€   110€
2    Sevilla   150€     70€      110€     120€   130€

In [288]:
df = df_exp.copy()

In [289]:
# df.set_index('Shop Name')

In [290]:
df = df[['Shop Name','Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']].replace('€', '',regex=True)

df.set_index('Shop Name')
ventas_tot = 0
n_ventas = 0
ventas_madrid = 0

for index in df.index:
    for x in df.loc[index][1:]:
        print(x)
        n_ventas += 1
        if index == 'Madrid':
            ventas_madrid += x

ventas_total = ventas_tot / n_ventas

ventas_total
ventas_madrid

100
90
120
100
70
200
80
150
90
110
150
70
110
120
130

0

In [291]:
precios = []
for c in df.values[:][:,1:]:
    print(c)
    for i in c:
        precios.append(int(i))
print(precios)

['100' '90' '120' '100' '70']
['200' '80' '150' '90' '110']
['150' '70' '110' '120' '130']
[100, 90, 120, 100, 70, 200, 80, 150, 90, 110, 150, 70, 110, 120, 130]

In [292]:
df_madrid = df_exp[df_exp["Shop Name"] == "Madrid"]
df_madrid = df_madrid.set_index('Shop Name').replace('€', '',regex=True)
df_madrid.values

array([['100', '90', '120', '100', '70']], dtype=object)

In [293]:
df[["Monday","Tuesday", "Wednesday", "Thursday", "Friday"]] = df[["Monday","Tuesday", "Wednesday", "Thursday", "Friday"]].astype(np.int32)

df[["Monday","Tuesday", "Wednesday", "Thursday", "Friday"]].mean(axis=1)

0     96.0
1    126.0
2    116.0
dtype: float64

In [294]:
df['avg_shop'] = df[["Monday","Tuesday", "Wednesday", "Thursday", "Friday"]].mean(axis=1)

df['avg_shop']

0     96.0
1    126.0
2    116.0
Name: avg_shop, dtype: float64

In [295]:
df

   Shop Name  Monday  Tuesday  Wednesday  Thursday  Friday  avg_shop
0     Madrid     100       90        120       100      70      96.0
1  Barcelona     200       80        150        90     110     126.0
2    Sevilla     150       70        110       120     130     116.0

# Ejercicio 3 
Feature Engineering con Regex, Str Ops, Numpy
- extrae las distancias y conviértelas a unidades con sentido

1.3.1. Crea una columna llamada distancias
- usa regex para extraer los números
- usa .astype() para convertirlos en el tipo adecuado

1.3.2. Crea una columna llamada unidades
- usa regex para extraer las unidades
- entiende los valores que aparecen en la columna unidad

1.3.3. Convierte las millas a kilómetros

In [296]:
#run this cell to create the dataset
df_distances = pd.DataFrame({
    "city1": ["Madrid", "Madrid", "Madrid", "London", "London", "London"],
    "city2": ["Barcelona", "Valencia", "Sevilla", "Manchester", "Liverpool", "Birmingham"],
    "distance": ["505 kilometres", "303KM", "390.5 km", "163 miles", "220 mi.", "miles: 120"]
})

In [297]:
df_distances

    city1       city2        distance
0  Madrid   Barcelona  505 kilometres
1  Madrid    Valencia           303KM
2  Madrid     Sevilla        390.5 km
3  London  Manchester       163 miles
4  London   Liverpool         220 mi.
5  London  Birmingham      miles: 120

In [298]:
df_distances['distances_num'] = df_distances['distance'].str.extract(r'(\d+\.?\d*)')[0].astype(float)

In [299]:
df_distances['distances_num']

0    505.0
1    303.0
2    390.5
3    163.0
4    220.0
5    120.0
Name: distances_num, dtype: float64

In [300]:
df_distances['distances_raw']=df_distances.distance.replace(to_replace=r"kilometres|KM|km|miles|:|mi\.", value="", regex=True)

In [301]:
df_distances = df_distances.drop('distances_raw', axis=1)

In [302]:
df_distances

    city1       city2        distance  distances_num
0  Madrid   Barcelona  505 kilometres          505.0
1  Madrid    Valencia           303KM          303.0
2  Madrid     Sevilla        390.5 km          390.5
3  London  Manchester       163 miles          163.0
4  London   Liverpool         220 mi.          220.0
5  London  Birmingham      miles: 120          120.0

In [303]:
df_distances['units'] = df_distances['distance'].str.extract(r'([a-zA-Z]+)')[0].str.lower()

In [304]:
df_distances['units']

0    kilometres
1            km
2            km
3         miles
4            mi
5         miles
Name: units, dtype: str

In [305]:
is_mile = df_distances['units'].isin(['miles', 'mi'])

In [306]:
df_distances['num2'] = df_distances['distances_num'].copy()

In [307]:
df_distances.loc[is_mile, 'distances_num'] = df_distances.loc[is_mile, 'distances_num'] * 1.609

In [308]:
df_distances['in_Km']=df_distances['distances_num'].copy()

In [309]:
df_distances

,city1,city2,distance,distances_num,units,num2,in_Km
0,Madrid,Barcelona,505 kilometres,505.000,kilometres,505.0,505.000
1,Madrid,Valencia,303KM,303.000,km,303.0,303.000
2,Madrid,Sevilla,390.5 km,390.500,km,390.5,390.500
3,London,Manchester,163 miles,262.267,miles,163.0,262.267
4,London,Liverpool,220 mi.,353.980,mi,220.0,353.980
5,London,Birmingham,miles: 120,193.080,miles,120.0,193.080

In [310]:
df_distances["in_Km2"] = 0

def to_km(row):
    #print(row)
    if "k" in row.units or "K" in row.units:
        return row.num2
    else:
        return row.num2 * 1.609  # 1 mile is equal to 1.609 km
    
df_distances["in_Km2"] = df_distances.apply(to_km, axis=1)

In [311]:
df_distances

,city1,city2,distance,distances_num,units,num2,in_Km,in_Km2
0,Madrid,Barcelona,505 kilometres,505.000,kilometres,505.0,505.000,505.000
1,Madrid,Valencia,303KM,303.000,km,303.0,303.000,303.000
2,Madrid,Sevilla,390.5 km,390.500,km,390.5,390.500,390.500
3,London,Manchester,163 miles,262.267,miles,163.0,262.267,262.267
4,London,Liverpool,220 mi.,353.980,mi,220.0,353.980,353.980
5,London,Birmingham,miles: 120,193.080,miles,120.0,193.080,193.080

# Ejercicio 4

Sin ejecutar este código, su resultado...

```python
import re

re.sub(r'e','a', 'hello my friends')
```
Elige la respuesta correcta:

    a. sustituye la 'e' por la 'a' en 'hello my friends'
    b. sustituye la 'a' for 'e' en 'hello my friends'
    c. sustituye la primera 'e' por la 'a'
    d. sustituye la primera 'a' por la 'e'

In [315]:
import re

re.sub(r's','h', 'estoy en python y me ha dado un coeficiente')

'ehtoy en python y me ha dado un coeficiente'

# Ejercicio 5

¿Qué devolverá la siguiente expresión regular que usa **lookbehind negativo**? (¡Cuidado! Es negativo).
Razona tu respuesta **SIN EJECUTAR** el código.

```python
import re

sentence = "I like python.\nI do not like Python."

re.findall(r'(?<!I\sdo\snot\slike\s)\w+\.',sentence)
```


Select the correct answer:

    a. ['python.', 'ython.']
    b. ['python.]
    c. ['I like python.\n']
    d. ['I like python.']

In [313]:
import re

sentence = "I like python.\nI do not like Python."

re.findall(r'(?<!I\sdo\snot\slike\s)\w+\.',sentence)

['python.', 'ython.']