# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [30]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [31]:
s1 = pd.Series(np.random.randint(1, 5, 100))
s2 = pd.Series(np.random.randint(1, 4, 100))  
s3 = pd.Series(np.random.randint(10000, 30001, 100))

print(s1)
print(s2)
print(s3)

0     1
1     2
2     3
3     4
4     4
     ..
95    4
96    1
97    3
98    2
99    1
Length: 100, dtype: int32
0     3
1     1
2     1
3     3
4     1
     ..
95    2
96    1
97    1
98    3
99    1
Length: 100, dtype: int32
0     26173
1     17079
2     11472
3     14510
4     28578
      ...
95    17440
96    24820
97    21602
98    25010
99    22400
Length: 100, dtype: int32

### Step 3. Let's create a DataFrame by joinning the Series by column

In [32]:
df = pd.concat([s1, s2, s3], axis=1)

df

    0  1      2
0   1  3  26173
1   2  1  17079
2   3  1  11472
3   4  3  14510
4   4  1  28578
.. .. ..    ...
95  4  2  17440
96  1  1  24820
97  3  1  21602
98  2  3  25010
99  1  1  22400

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [33]:
df.columns = ['bedrs', 'bathrs', 'price_sqr_meter']
df

    bedrs  bathrs  price_sqr_meter
0       1       3            26173
1       2       1            17079
2       3       1            11472
3       4       3            14510
4       4       1            28578
..    ...     ...              ...
95      4       2            17440
96      1       1            24820
97      3       1            21602
98      2       3            25010
99      1       1            22400

[100 rows x 3 columns]

### Step 5. Create a column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [34]:
bigcolumn = pd.concat([s1, s2, s3], axis=0).to_frame()
bigcolumn

        0
0       1
1       2
2       3
3       4
4       4
..    ...
95  17440
96  24820
97  21602
98  25010
99  22400

[300 rows x 1 columns]

In [35]:
df

    bedrs  bathrs  price_sqr_meter
0       1       3            26173
1       2       1            17079
2       3       1            11472
3       4       3            14510
4       4       1            28578
..    ...     ...              ...
95      4       2            17440
96      1       1            24820
97      3       1            21602
98      2       3            25010
99      1       1            22400

[100 rows x 3 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [36]:
bigcolumn.index

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       ...
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype='int64', length=300)

In [37]:
len(bigcolumn)
# No parece, asumo que es porque repite los indice de las 3 series por separado

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [38]:
bigcolumn = bigcolumn.reset_index()
bigcolumn

     index      0
0        0      1
1        1      2
2        2      3
3        3      4
4        4      4
..     ...    ...
295     95  17440
296     96  24820
297     97  21602
298     98  25010
299     99  22400

[300 rows x 2 columns]

In [39]:
bigcolumn.index

RangeIndex(start=0, stop=300, step=1)

In [47]:
bigcolumn = bigcolumn.drop(['index'], axis=1)

In [49]:
bigcolumn.columns = ['bignum']

In [50]:
bigcolumn

     bignum
0         1
1         2
2         3
3         4
4         4
..      ...
295   17440
296   24820
297   21602
298   25010
299   22400

[300 rows x 1 columns]